### ISSUE TITLE
Support punctuation in Conventional Commit Message.

### ISSUE THREAD

**Issue by Notmeagain** [bk201-/jira-prepare-commit-msg#192]
`const conventionalCommitRegExp = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\)!?)?: ([\w ]+)$/g;
`

should change to:

`const conventionalCommitRegExp = /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\)!?)?: ([\w \S]+)$/g;`

Issue:
When using Conventional Commits and you type a message like:

`chore(deps): Finally solved that problem!`

the regex fails to identify the message part, resulting in the jira ticket number being added in the wrong place.

**Comment by bk201-** [comment]
Hi @Notmeagain!

I fixed it! Please, update it to the latest version. Thanks!
