### ISSUE TITLE
Is this package also compatible with yorkie?

### ISSUE THREAD

**Issue by alex-w0** [bk201-/jira-prepare-commit-msg#201]
Hi, I'ld like to use this package with [Yorkie ](https://www.npmjs.com/package/yorkie) (which is a fork from husky).
Is this possible?

**Comment by bk201-** [comment]
Hi @alex-w0! Yorkie and Husky have only one different thing that can affect this package: finding the git folder. 

Git runs Node.js process with the hook from .git/hooks. After that, it runs the following command
```javascript
cp.spawnSync('git', ['rev-parse', '--show-prefix', '--git-common-dir'], { cwd });
```

Based on the above I can conclude that it should work. I checked it on a simple project, and it also worked fine. But Yorkie is used for monorepo. Unfortunately, I didn't have the opportunity to check it.

**Comment by alex-w0** [comment]
Hi @bk201- , unfortunately I cannot reproduce anymore the problem, because i tried it on another device.
But since I do not use a monorepo either for my project, I replaced it with husky where it works fine :+1:
