### ISSUE TITLE
Append ticket number at the bottom of the commit message

### ISSUE THREAD

**Issue by MizdaCollinz** [bk201-/jira-prepare-commit-msg#22]
Would be desirable configurability to be able to attach the ticket at the bottom of the commit message (preferably with a blank line before it) so that it is in the "body" of the commit message.

This would allow this tool to be used while following the conventional-commits spec
https://www.conventionalcommits.org/en/v1.0.0-beta.2/ and to avoid breaking commit linting.

**Comment by bk201-** [comment]
Hi @MizdaCollinz! Please take a look at #49
