### ISSUE TITLE
Missing space before ticket ID

### ISSUE THREAD

**Issue by FDiskas** [bk201-/jira-prepare-commit-msg#26]
I found better online command
```
git branch | grep -o "\* \(.*/\)*[A-Z]\{2,\}-[0-9]\+" | grep -o "[A-Z]\{2,\}-[0-9]\+"
```

Source https://bitbucket.org/snippets/atlassian/qedp7d

**Comment by bk201-** [comment]
Hi @FDiskas! Please take a look at #49 

You can set jiraTicketPattern like '([A-Z]{2,}-[0-9]+)'
