### ISSUE TITLE
Error: The process.env.HUSKY_GIT_PARAMS isn't set. Is supported Husky version installed?

### ISSUE THREAD

**Issue by leannepatmoretsl** [bk201-/jira-prepare-commit-msg#277]
HUSKY_GIT_PARAMS have been removed in the latest update of husky, which is throwing the above error when running the `jira-prepare-commit-msg` hook.

More information can be found here: https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-

### Version
```
"jira-prepare-commit-msg": "1.5.1",
"husky": "5.0.9"
```

**Comment by bk201-** [comment]
Hi @leannepatmoretsl! Unfortunately, I wasn't watching Husky version, I didn't know about new version 5 with breaking changes. I'm going to take a look next 2-3 days. thanks

**Comment by leannepatmoretsl** [comment]
Thank you! And thank you for the super quick response.

**Comment by bk201-** [comment]
Hi @leannepatmoretsl! I've fixed it in version 1.5.2. Please check it

**Comment by leannepatmoretsl** [comment]
Looks great and working perfectly, thank you so much
