### ISSUE TITLE
using jira-prepare-commit-msg with husky >= 5 does not work as documented on npm/npx >= 7

### ISSUE THREAD

**Issue by anthony-telljohann** [bk201-/jira-prepare-commit-msg#308]
Please see https://github.com/typicode/husky/issues/924 for more info.

**Comment by jmtelljohann** [comment]
I had the same problem

**Comment by bk201-** [comment]
Hi! I've checked the issue. Unfortunately, I couldn't repro this. I've done the following steps:
I use Windows. If you have another system, please ping me, I will check it on Linux.
1. Create a new folder
2. `git init`
3. `npm init`
4. `npm install husky -D`
5. `npm set-script prepare "husky install"`
6. `npm run prepare`
7. `npx husky add .husky/prepare-commit-msg 'npx --no-install jira-prepare-commit-msg "$1"'`
![image](https://user-images.githubusercontent.com/6812525/114154325-f0a4b600-9928-11eb-9f5f-fdbfef60103b.png)
8. Check file `.husky/prepare-commit-msg`
![image](https://user-images.githubusercontent.com/6812525/114154540-2fd30700-9929-11eb-98ae-7d1263d4fdd2.png)

**Comment by anthony-telljohann** [comment]
We tested on macOS with Terminal.app using a bash shell, and on Windows with Git Bash using a bash shell.

**Comment by bk201-** [comment]
Still can't repro on Windows
![image](https://user-images.githubusercontent.com/6812525/114173066-379da600-993f-11eb-8604-2f9938b92e62.png)

**Comment by anthony-telljohann** [comment]
@bk201- I tried reproducing in centos 7 but failed to do so as well. I'm going to try testing on macOS again.

**Comment by anthony-telljohann** [comment]
@bk201- likewise, I was not able to reproduce this experience on macOS. I suspect the problem my wife and I experienced may be related to migrating a repo with existing hooks.

I will test that theory too.

**Comment by anthony-telljohann** [comment]
We figured out the problem: It does not work as documented when using `npm`/`npx` `@^7.0.0` but does work as documented with `npm`/`npx` `@^6.0.0`.

**Comment by bk201-** [comment]
@anthony-telljohann 
Hm... I tested on Windows with npm@7.8.0. It worked perfectly. I'm going to try this on Linux tomorrow, but I haven't got MacOS.

**Comment by bk201-** [comment]
![image](https://user-images.githubusercontent.com/6812525/114388118-f3f3a800-9b9b-11eb-8f44-81f672909919.png)
![image](https://user-images.githubusercontent.com/6812525/114388424-551b7b80-9b9c-11eb-9593-ca310bfa1e54.png)

I reproduced it on Linux. But I'm sure it isn't my issue. 
I tried to debug npm, and find next:

npm@6
![image](https://user-images.githubusercontent.com/6812525/114401529-ada64500-9bab-11eb-8e86-0f5bc60c2041.png)

It runs husky as a module (point 1), not as a cmd (point 2)

npm@7
![image](https://user-images.githubusercontent.com/6812525/114402408-75ebcd00-9bac-11eb-8537-ffc8bb210978.png)

It creates the following arguments
``` 
sh [
  '-c',
  'husky "add" ".husky/prepare-commit-msg" "npx --no-install jira-prepare-commit-msg \\"$1\\""'
]
```

I closed the issue and moved the conversation to husky issues

**Comment by the-ult** [comment]
With npm@7 I kept getting errors with Husky.

adding: `--yes` fixed it.
`npx --yes --no-install jira-prepare-commit-msg "$1"`

see: https://omrilotan.medium.com/npx-breaking-on-ci-b9f3f61d4676

**Comment by bk201-** [comment]
@the-ult Interesting. It looks like a new issue. Because this hook doesn't wait for anything. Maybe npm@7 exec does something wrong. Please create a new issue, because I may forget about this problem. I want to investigate how works npm@7 )

Honestly, I'm tired of the new npm, it brings so many breaking changes

Thanks!
