### ISSUE TITLE
Aborting commit message should abort commit

### ISSUE THREAD

**Issue by robertmassaioli** [bk201-/jira-prepare-commit-msg#319]
Expected behaviour: I use Vim for my commit messages, when I type in `:qa!` to abort the commit message then a commit should not occur.

Actual behaviour: I get a commit message with just the Jira key in the message and my changes are saved.

What would we have to modify such that if the editor aborts the message so too does jira-prepare-commit-msg?

**Comment by robertmassaioli** [comment]
For those watching this, a workaround, for now, is just deleting the text that was added to the commit before exiting your editor. That will be seen by git as an empty commit message and your commit will be aborted.

**Comment by bk201-** [comment]
Hi @robertmassaioli!

Please check it with version 1.6.0
