### ISSUE TITLE
1.6.0 - env: node\r: No such file or directory

### ISSUE THREAD

**Issue by adamtay** [bk201-/jira-prepare-commit-msg#349]
When using `jira-prepare-commit-msg@1.6.0`, getting the following issue in terminal `env: node\r: No such file or directory`.

Downgrading to `1.5.1` has resolved it.

**My environment:**
**OS:** macOS 10.14.6
**Node:** 12.16.2
**NPM:** 6.14.4
**Yarn:** 1.22.10 (my project is using Yarn).

**Comment by ghry5** [comment]
seems to be caused by incorrect line endings in `node_modules/.bin/jira-prepare-commit-msg`. 
Setting the mentioned file to `LF` line endings fixes the issue untill next npm/yarn install.

**Comment by bk201-** [comment]
Fixed at 1.6.1
