### ISSUE TITLE
Commit message contains new line between JIRA issue and message

### ISSUE THREAD

**Issue by adamtay** [bk201-/jira-prepare-commit-msg#350]
I understand that this is customizable but just wondering why is the default behavior to include a `\n` between the JIRA issue and commit message?

This means when creating a PR in BitBucket, the default PR title would only contain the JIRA issue, for example `[JIRA-123]` rather than infer the PR title from the commit message.

**Comment by DannyFeliz** [comment]
Yeah, it's a little bit weird for me too, I had to change that

**Comment by bk201-** [comment]
In general, I agree.  At one of my prev projects, we had to use a newline between the JIRA ticket and commit message, so it moved here.

I'll change this, but it will be breaking changes

**Comment by bk201-** [comment]
Fixed at 1.6.1
