### ISSUE TITLE
Error: The JIRA ticket ID not found when branch contains digit

### ISSUE THREAD

**Issue by coolweb** [bk201-/jira-prepare-commit-msg#442]
When branch name contains digits like feature/FOFRD36 the following error occurs: Error: The JIRA ticket ID not found.
In the code there is a regex: jiraTicketPattern: '([A-Z]+-\\d+)'
with this regex it works: ([A-Z0-9]+-\\d+)

Could you make it works with digit?

**Comment by DennisBoanini** [comment]
> When branch name contains digits like feature/FOFRD36 the following error occurs: Error: The JIRA ticket ID not found. In the code there is a regex: jiraTicketPattern: '([A-Z]+-\d+)' with this regex it works: ([A-Z0-9]+-\d+)
> 
> Could you make it works with digit?

I do not understand well this issue: the jiraTicketPattern: '([A-Z]+-\d+)' it's only an example, you can use any custom expression for the jiraTicketPattern field

**Comment by coolweb** [comment]
Sorry I have not seen that we can configure it, I found  jiraTicketPattern: '([A-Z]+-\d+)' in the source code. Thx for your reply.
