### ISSUE TITLE
the configuration not working on different machine 

### ISSUE THREAD

**Issue by Chat24-7** [bk201-/jira-prepare-commit-msg#504]
I have setup the jira-prepare-commit-msg & huskey on my windows machine and its working fine means whenever I commit it's appending jira-id into my commit msg. I pushed and merged my changes to the master branch and take pull to a different machine(mac)
on mac machine, the Jira id is not appending. **do I have to setup as mentioned in the doc on every machine?**

**Comment by bk201-** [comment]
Hi @Chat24-7!

Could you please provide the log from the console when you do commit on mac? To add more details to the console, use:
```bash
git commit -m "<message>" --verbose
```

**Comment by bk201-** [comment]
Closed due to the conversation has not been updated for more than half a year
