### ISSUE TITLE
Feature Request - Quite output

### ISSUE THREAD

**Issue by webdevnerdstuff** [bk201-/jira-prepare-commit-msg#580]
It would be nice if there was a way to silent the output on the cli, and just have it run in the background.

**Comment by webdevnerdstuff** [comment]
I did a quick test, and it seems like something easy to add. I'll put in a pull request for you to check out.

**Comment by webdevnerdstuff** [comment]
https://github.com/bk201-/jira-prepare-commit-msg/pull/581

new flag `--quiet`

**Comment by bk201-** [comment]
Merged! Thank you for your contribution!

**Comment by webdevnerdstuff** [comment]
Put in another pull request to fix my if flag check. I was looking at the verbose one and my hands just took over and added the `!` by accident.

https://github.com/bk201-/jira-prepare-commit-msg/pull/582

**Comment by bk201-** [comment]
Some minutes, I will update the npm package

**Comment by webdevnerdstuff** [comment]
Thank you. :)
