### ISSUE TITLE
Makes nothing

### ISSUE THREAD

**Issue by OnkelTem** [bk201-/jira-prepare-commit-msg#661]
After installation, I cannot trigger its activity: I make commits, but  `jira-repare-commit-msg` does nothing.
How it should look, when it's installed and working? Which files, where?
In my `.husky/` directory there is only one file: the default sample `pre-commit`.

node 16
npm 8
kubuntu 22.04

**Comment by OnkelTem** [comment]
https://github.com/bk201-/jira-prepare-commit-msg/pull/662

**Comment by bk201-** [comment]
As I understand, you've already fixed the issue, haven't you?
