### ISSUE TITLE
conventional commit scope is optional

### ISSUE THREAD

**Issue by darraghoriordan-roam** [bk201-/jira-prepare-commit-msg#79]
Hey, 

thanks for creating this! I think there is a tiny issue where the conventional commit specification allows scope to be optional. So `fix: my message` is a valid message. `fix(backend): my message` is the same but with a `(backend)` scope. The regex used in the code returns `undefined` when it can't match scope. 

This currently gets written back to the commit message as `undefined` which is incorrect and break the conventional commit. e.g. `fixundefined: JIRA-999 my message`.

It's easy to fix though! Line 145 of git.ts you can replace the scope wit an empty string if it's not set. 

 ```
lines[0] = `${type}${scope || ''}: ${replaceMessageByPattern(jiraTicket, msg, config.messagePattern)}`;
```

Now we get `fix: JIRA-999 my message` 👍Sorry, I cant create PRs here.

**Comment by bk201-** [comment]
Hi!

Thank you a lot for finding this bug. I fixed it in 1.3.2. Please, upgrade to the latest version.
