### ISSUE TITLE
Scope `undefined` fix not published in latest package.

### ISSUE THREAD

**Issue by aga5tya** [bk201-/jira-prepare-commit-msg#98]
The fix part of https://github.com/bk201-/jira-prepare-commit-msg/commit/be599ee61c1221ce4b974a241de605e7c619c67e doesn't seem to appear in final build

https://unpkg.com/jira-prepare-commit-msg@1.3.2/bin/git.js

@bk201

**Comment by bk201-** [comment]
Hi @aga5tya!

Sorry, it was my mistake, I've updated the package. Please check the v1.3.3
